#!/bin/bash
#
###########################################################################
# (C) Copyright IBM Corporation 2016.                                     #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#      http://www.apache.org/licenses/LICENSE-2.0                         #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
###########################################################################

if [ $# != 3 ]; then
  echo "Usage: build <version> <IBMid> <IBMid password>"
  exit 1
fi

docker build -t installation-manager . --build-arg VERSION=$1 --build-arg IBM_ID=$2  --build-arg IBM_PASSWORD=$3|| exit $?

# copy the intermediate artifacts from /target

docker run installation-manager cat /target/ihs$1.tar.gz > im/ihs$1.tar.gz
docker run installation-manager cat /target/Dockerfile.$1 > im/Dockerfile.$1

# Build image from hosted tar file
echo "Building image"
docker build -t ibm-http-server:$1 -f im/DockerFile.$1 . || exit $?
