#!/bin/bash
#
###########################################################################
# (C) Copyright IBM Corporation 2016.                                     #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#      http://www.apache.org/licenses/LICENSE-2.0                         #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
###########################################################################

if [ $# != 3 ]; then
  echo "Usage: build <version> <IBMid> <IBMid password>"
  exit 1
fi

docker build -t installation-manager im || exit $?
docker run --rm -v $(pwd):/host installation-manager /host/install_ihs $1 $2 $3 || exit $?

docker run -d --name tar_server -v $(pwd)/ihs$1.tar.gz:/host/ihs$1.tar.gz -w /host python:2-slim python -m SimpleHTTPServer
tar_server_ip=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' tar_server)
tar_url="http://${tar_server_ip}:8000/ihs${1}.tar.gz"


# Build image from hosted tar file
echo "Building image"
docker build -t ibm-http-server:$1 --build-arg TAR_URL=$tar_url . || exit $?
docker rm -f tar_server
