#!/bin/bash
#
###########################################################################
# (C) Copyright IBM Corporation 2020.                                     #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#      http://www.apache.org/licenses/LICENSE-2.0                         #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
###########################################################################

if [ $# != 1 ]; then
  echo "Usage: push_all <registry>"
  exit 1
fi

while read line; do
  if [[ $line == \#* ]]; then continue; fi
  version=$(cut -d, -f1 <<< $line)
  docker tag ibm-http-server:${version}-ubi $1/ibm-http-server:${version}-ubi
  docker push $1/ibm-http-server:${version}-ubi
done < versions.csv

#Add latest tag and push to the last build image
docker tag $1/ibm-http-server:${version}-ubi $1/ibm-http-server:latest
docker push $1/ibm-http-server:latest

