#!/bin/sh
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /opt/IHS/logs/httpd.pid

if [ -f /opt/IHS/bin/envvars ]; then
  . /opt/IHS/bin/envvars
fi

exec /opt/IHS/bin/httpd -d /opt/IHS -DFOREGROUND "$@"